<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SideBar</name>
   <tag></tag>
   <elementGuidId>8e2a45a6-127e-4442-b0e2-f8a5f0fdc111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;logo&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41baaf4d-02df-4f55-b778-afc985a9816d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/logo-enigma.svg</value>
      <webElementGuid>f722703a-76fc-420b-a139-5463ec244aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>c31f5866-f020-459f-b1e9-f7566a49b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>8d55accb-83de-4e95-8503-bcb984ddafcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[1]/div[@class=&quot;wrapper-container&quot;]/div[@class=&quot;ec-bg-neutral-50 sidebar&quot;]/div[@class=&quot;header ec-fs-5 fw-medium&quot;]/div[@class=&quot;col illustration d-flex flex-row justify-content-between mt-0&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>1f91cf7e-5191-44ae-8753-68b461920d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>15450b42-c1e1-4013-a8d0-a9d2ed2be425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e0bc1a11-25fd-4e22-a896-f5a2d7fc7cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/logo-enigma.svg' and @alt = 'logo']</value>
      <webElementGuid>b839cef3-8d3b-49da-8c58-de86accfb95b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
