<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Back</name>
   <tag></tag>
   <elementGuidId>52f2051c-ebab-4b62-b8cd-4659b043f8ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-neutral-800</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Back')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Back&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e925e1b-e1f4-4957-b4e9-88e84c0d2e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-neutral-800</value>
      <webElementGuid>2413c3d7-429f-42ac-a87c-4cd3b4501b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Back</value>
      <webElementGuid>577ce92f-bbef-4b7a-afb9-0528688611eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[1]/div[@class=&quot;wrapper-container&quot;]/div[@class=&quot;main-content no-scrollbar&quot;]/div[@class=&quot;d-flex flex-column z-1 position-relative&quot;]/app-my-course[1]/div[@class=&quot;col-11 mx-auto&quot;]/div[@class=&quot;d-flex flex-column pt-0&quot;]/div[@class=&quot;col-12 ec-fs-5 pb-3&quot;]/app-back-button[1]/nav[1]/div[@class=&quot;py-3&quot;]/a[@class=&quot;text-neutral-800&quot;]</value>
      <webElementGuid>7b21494d-d2ad-4872-9df2-5c06306ae94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back')]</value>
      <webElementGuid>173fd6ee-e033-4b2b-b33a-7962ddfdf2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Course'])[2]/following::a[1]</value>
      <webElementGuid>9cfbf5b2-f6ca-45de-ac2b-56ad06c77f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Course'])[1]/following::a[1]</value>
      <webElementGuid>18abbbb9-b299-427b-8a1c-2082afa6c8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are not enrolled in any program'])[1]/preceding::a[1]</value>
      <webElementGuid>ab4a571f-e105-49d7-a95c-62b89243b1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Course'])[1]/preceding::a[1]</value>
      <webElementGuid>76697e32-b7a9-42fd-9306-174a62ee2c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a</value>
      <webElementGuid>2767120b-1322-4093-8edf-a10dd50ea37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '  Back' or . = '  Back')]</value>
      <webElementGuid>f8aa0652-acc2-437d-95be-371fdcb765fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
